# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build Totem Keyboard"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["totem_dongle dongle_display"]'
      branches: '["zmkfirmware/zmk/v0.3-branch"]'
